= arinc665_media_set_compiler(1)
Thomas Vogt

== Name

arinc665_media_set_compiler - compiles ARINC 665 Media Sets based on an XML Configuration file.

== Synopsis

*arinc665_media_set_compiler*
-f|--xml-file _XML File_
{-s|--source-directory _Source_}
[-b|--create-batch-files None|NoneExisting|All]
[-l|--create-load-header-files None|NoneExisting|All]
[-v|--version Supplement2|Supplement345]
[-d|--destination-directory _Destination_]
[-n|--media-set-name _Name_]

The media set is generated within the directory `_Destination_/_Name_`.

== Options

// tag::options[]
*-f|--xml-file* _XML File_::
Path to ARINC 665 Media Set description XML file.

*-s|--source-directory* _Source_::
Source of Media Set files.

*-b|--create-batch-files* None|NoneExisting|All::
Indicates if Load Header files shall be created or not.

*-l|--create-load-header-files* None|NoneExisting|All::
Indicates if Batch files shall be created or not.

*-v|--version* Supplement2|Supplement345::
ARINC 665 Media Set version.

*-d|--destination-directory* _Destination_::
Output directory for ARINC 665 media set.
If not set, the current directory is used.

*-n|--media-set-name _Name_::
Media Set name to be used.
If not provided, the part number of the media set ist used.

== See Also

link:[arinc665_media_set_decompiler(1)]
